nombre = input("¿cual es tu nombre y apellidos?")
print("Hola, Sr. o Sra.",(nombre))
a = int(input("¿me das un numero?"))
b = int(input("¿me das otro numero?"))
print("su multiplicación es",(a * b))
c = int(input("¿me das un numero?"))
print("la operación de a+b)*c es:",(a+b)*c)
print("la operación de a*c + b*c es:",a*c + b*c)
d = int(input("dame un numero entero"))
e = int(input("dame otro numero entero"))
print("su división es: ", d/e)
f = int(input("dame un numero al que pueda elevar el 2"))
print("el 2 elevado a tu numero es:",2**f)
g = float(int(input("dame un numero")))
h = float(int(input("dame otro numero")))
print("su division sin decimales es:", g//h)
i = int(input)("dame un numero entero")
j = int(input)("dame otro numero entero")
print("su divison es:",i/j )